### ISSUE TITLE
Distributions.jl dependency

### ISSUE THREAD

**Issue by jtackm** [juliangehring/Bootstrap.jl#72]
Thank you for this great package. Would it be possible set to a proper `[compat]` entry in Project.toml or remove Distributions.jl from the dependency list? As is, Bootstrap leads to my Distributions.jl version being downgraded:

```
(@v1.5) pkg> add Bootstrap
  Resolving package versions...
  Installed StatsFuns ─ v0.9.6
  Installed Requires ── v1.1.1
  Installed RCall ───── v0.13.10
  Installed Revise ──── v3.1.8
Updating << path removed >>
  [e28b5b4c] + Bootstrap v2.2.0
  [31c24e10] ↓ Distributions v0.24.3 ⇒ v0.23.12
```

**Comment by juliangehring** [comment]
Should be fixed by #74 and the release of v2.2.1.

**Comment by jtackm** [comment]
Unfortunately still the same issue:

```julia
(@v1.5) pkg> add Bootstrap
  Resolving package versions...
  Installed Bootstrap ──────── v2.2.1
  Installed IJulia ─────────── v1.23.1
  Installed Dictionaries ───── v0.3.5
  Installed FileIO ─────────── v1.4.5
  Installed CSV ────────────── v0.8.2
  Installed HDF5 ───────────── v0.14.2
  Installed DataFrames ─────── v0.22.1
  Installed Revise ─────────── v3.1.9
  Installed OnlineStats ────── v1.5.8
  Installed NearestNeighbors ─ v0.4.8
Updating << path removed >>
  [e28b5b4c] + Bootstrap v2.2.1
  [336ed68f] ↑ CSV v0.8.0 ⇒ v0.8.2
  [944b1d66] ↑ CodecZlib v0.6.0 ⇒ v0.7.0
  [a93c6f00] ↑ DataFrames v0.22.0 ⇒ v0.22.1
  [85a47980] ↑ Dictionaries v0.3.2 ⇒ v0.3.5
  [31c24e10] ↓ Distributions v0.24.6 ⇒ v0.23.12
  [5789e2e9] ↑ FileIO v1.4.4 ⇒ v1.4.5
  [f67ccb44] ↑ HDF5 v0.14.1 ⇒ v0.14.2
  [7073ff75] ↑ IJulia v1.23.0 ⇒ v1.23.1
  [b8a86587] ↑ NearestNeighbors v0.4.7 ⇒ v0.4.8
  [a15396b6] ↑ OnlineStats v1.5.7 ⇒ v1.5.8
  [295af30f] ↑ Revise v3.1.8 ⇒ v3.1.9

[ ... ]
```

When manually trying to reinstall the latest Distributions.jl version:

```julia
(@v1.5) pkg> add Distributions@v0.24.6
  Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Distributions [31c24e10]:
 Distributions [31c24e10] log:
 ├─possible versions are: [0.16.0-0.16.4, 0.17.0, 0.18.0, 0.19.1-0.19.2, 0.20.0, 0.21.0-0.21.3, 0.21.5-0.21.12, 0.22.0-0.22.6, 0.23.0-0.23.12, 0.24.0-0.24.6] or uninstalled
 ├─restricted to versions 0.18-0.24 by LsqFit [2fda8390], leaving only versions [0.18.0, 0.19.1-0.19.2, 0.20.0, 0.21.0-0.21.3, 0.21.5-0.21.12, 0.22.0-0.22.6, 0.23.0-0.23.12, 0.24.0-0.24.6]
 │ └─LsqFit [2fda8390] log:
 │   ├─possible versions are: 0.11.0 or uninstalled
 │   └─LsqFit [2fda8390] is fixed to version 0.11.0
 ├─restricted to versions 0.24.6 by an explicit requirement, leaving only versions 0.24.6
 └─restricted by compatibility requirements with Bootstrap [e28b5b4c] to versions: [0.16.0-0.16.4, 0.17.0, 0.18.0, 0.19.1-0.19.2, 0.20.0, 0.21.0-0.21.3, 0.21.5-0.21.12, 0.22.0-0.22.6, 0.23.0-0.23.12] — no versions left
   └─Bootstrap [e28b5b4c] log:
     ├─possible versions are: [2.0.0-2.0.1, 2.1.0, 2.2.0-2.2.1] or uninstalled
     └─restricted to versions * by an explicit requirement, leaving only versions [2.0.0-2.0.1, 2.1.0, 2.2.0-2.2.1]
```

**Comment by juliangehring** [comment]
@jtackm v2.3.1 should allow you to use `Distributions ` v0.24.

**Comment by jtackm** [comment]
Can confirm, thank you for the work
